### ISSUE TITLE
Bad and missing help text for `stack` commands

### ISSUE THREAD

**Issue by Nuru** [spacelift-io/spacectl#19]
The [v0.6.0 README](https://github.com/spacelift-io/spacectl/tree/b2d1b4e88114d25c5726d723454317ec31afccb9#readme) does not have any information about the command `spacectl stack set-current-commit`.

The `help` output in version 0.6.0 is misleading and in some cases missing.

<details><summary>Click to show full output</summary>

```
$ spacectl stack --help
NAME:
   spacectl stack - Manage a Spacelift stack

USAGE:
   spacectl stack command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command
   Run local preview:
     local-preview  Start a preview (proposed run) based on the current project. Respects .gitignore and .terraformignore.
   Run management:
     confirm  Confirm an unconfirmed tracked run
     deploy   Start a deployment (tracked run)
     logs     Show logs for a particular run
     preview  Start a preview (proposed run)
     task     Perform a task in a workspace
   Stack management:
     set-current-commit  Set current commit on the stack

OPTIONS:
   --id value  User-facing ID (slug) of the stack
   --help, -h  show help (default: false)
 ```

</details>

Specifically
```
USAGE:
  spacectl stack command [command options] [arguments...]

COMMANDS:
  ....
   set-current-commit

OPTIONS:
  --id value
```
suggests that `command` can be replaced by `set-current-commit` and `--id value` should follow it, since there is no other place shown for options to appear on the command line. However, 
```
spacectl stack set-current-commit --help
```
yields the error `Required flag "id" not set` and shows the list of subcommands to `spacectl stack`, whereas I expected it to list arguments and options for the `set-current-command` command. It also implies that `--id value` is not an "Option" but a requirement. So the usage should be something more like
```
spacectl stack (--id value | --help) command [command options] [arguments...]
```

To get help for the `set-current-commit` I have to give the unintuitive and not properly documented command:
```
$ spacectl stack --id placeholder set-current-commit --help
USAGE:
   spacectl stack set-current-commit [command options] [arguments...]
...
```
which has no documentation for any arguments `set-current-commit` might take and again lists `--sha` as an "Option" when it appears to be required. 

Please document `set-current-commit` fully and properly.

**Comment by adamconnelly** [comment]
@Nuru this has been fixed in [version 0.7.0](https://github.com/spacelift-io/spacectl/releases/tag/v0.7.0). We've made the following changes:

- The `--id` parameter is optional unless running a command where the `--id` is required.
- We've updated all of the commands to follow the format `spacectl <command> <sub-command> [Options] [arguments...]`.
- Required parameters are marked with `[Required]` in the help output.
- The README has been updated to remove the detailed usage information since it's available by using the help command / option.

Here's an example of getting the help for the `set-current-commit` command now:

```shell
$ spacectl stack set-current-commit --help
NAME:
   spacectl stack set-current-commit - Set current commit on the stack

USAGE:
   spacectl stack set-current-commit [command options]  

CATEGORY:
   Stack management

OPTIONS:
   --id ID     [Required] User-facing ID (slug) of the stack
   --sha SHA   [Required] SHA of the commit to set as canonical for the stack
   --help, -h  show help (default: false)
```

You can see that the `--id` parameter doesn't need to be specified anymore, and the required parameters are marked in the output.

Thanks for the feedback!
