### ISSUE TITLE
Request: drain and undrain workers

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/spacectl#68]
It would be nice to drain and undrain workers using the spacectl

**Comment by spr-mweber3** [comment]
@adamconnelly My colleague and I are on it to address this issue in an upcoming PR. Do you have any early suggestions on what to consider when we implement that?

**Comment by adamconnelly** [comment]
@spr-mweber3 just adding the info we talked about on Slack here as well.

You need to use the `workerDrainSet(workerPool: ID!, id: ID!, drain: Boolean!): Worker!` mutation to drain/undrain a worker, passing the `drain` variable as `true` if you want to drain and `false` if you want to un-drain.

Behind the scenes not much happens other than marking the worker as drained/un-drained. The only thing different that happens when un-draining is we trigger scheduling on the worker pool since there's a new worker available for scheduling runs.

**Comment by spr-mweber3** [comment]
#84
